### PR TITLE
Display app version

### PR DESCRIPTION
**Pull request by orkestrov**
We store AppVersion from nodes in `node_health` table and display it on /web/status page. This is thought to improve convenience of monitoring and debugging.

### CODE REVIEW

**Comment by orkestrov** [comment]
A minor bug was introduced here: the [Active] host is not marked anymore. I will fix this soon.

**Comment by shlomi-noach** [comment]
In what sense it it not "marked"?

**Comment by orkestrov** [comment]
On the status page (/web/status) [Active] label is not shown next to the active node anymore. The problem is in status.js I believe, operation should not be affected (we are running this version for several days without visible problems).

**Comment by shlomi-noach** [comment]
Thanks for elaborating. So this is a minor visualization problem.

**Comment by orkestrov** [comment]
Fixed in https://github.com/outbrain/orchestrator/pull/243

**Pull request merged**
