### PR TITLE
Moved files to go structure

### PR DESCRIPTION
**Pull request by shuhaowu**
Ref: #60 

I tried this although there's some issues with the build script, it seems to modify the user's GOPATH and also makes some other assumptions: assumes GOPATH=/usr/share/golang, assumes users have fpm installed, and so forth. I'll create another question issue for some of the things I've found while trying to figure out how this project works.

Either way this should make this repository more like traditional go projects.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Thank you, merged, and will follow up

**Comment by shlomi-noach** [comment]
Grrrrr. I see some trouble here. But getting late right now. Will rollback this one for now and write a more thorough review tomorrow.

**Comment by shuhaowu** [comment]
:+1: Thanks.

**Comment by shlomi-noach** [comment]
Sorry - reverted for the meantime as this broke a few things. I'll find the
time to provide good review on this.

**Comment by shlomi-noach** [comment]
Courtesy @dgryski orchestrator is now go-getttable. Thanks both!

**Pull request merged**
