### PR TITLE
Update go sql driver and readTimeout

### PR DESCRIPTION
**Pull request by orkestrov**
We had a couple of misbehaving DB machines in our environment.
The kernel was able to accept and serve tcp connections
but mysqld was unresponsive. As a result, plenty of discovery
goroutines in Orchestrator would hang forever on sql.Query
calls.
    
We've chosen 10s as a default read timeout for both
topology and backend reads. We think 10 seconds is a
safe bet: If db hosts or backend are not responding
that long then there must be a problem that should
be handled specially.

We had to update go-sql-driver on the way as read/write
timeouts were not supported in the older version. Skimming
through the commit history of go-sql-driver left me with
an impression that changes are not critical. We've run
the newer version of the driver for a few days and have not seen
any issues.

### CODE REVIEW

**Comment by orkestrov** [comment]
sjmudd convinced me that we should not depend on govendor to build the project. So I included driver code and removed .gitignore and build.sh changes in the last commit.

**Comment by shlomi-noach** [comment]
@orkestrov Booking.com is likely the best testbed for this; if you ran this in production for a few days and got no error this, I'm happy.

Can you please just elaborate on which version this is of `go-sql-driver`? Is it just latest `master`? Any particular version number I can write down?

> sjmudd convinced me that we should not depend on govendor to build the project. So I included driver code and removed .gitignore and build.sh changes in the last commit.

I'm afraid I didn't quite follow that^,

**Comment by sjmudd** [comment]
Shlomi: look in vendor/vendor.json. The nice thing about govendor is it provides clear commit info and location of the files being imported and later you can easily check if you are in sync and update with a single command. So the exact version of the go-sql-driver is the latest one. No need to write anything down this is updated by govendor (when you tell it to) automatically.

**Comment by sjmudd** [comment]
Bottom line: if the tcp connection via the go driver to the server is up, when you send a command it may take a very long time (at least 60 seconds, but I think more) before you get any response back. Consequently this ties up resources on the go side. They may not be very heavy but we don't expect a mysql server to take more than ~1 second to service any of the discovery queries. If it does it's "sick", and thus allowing the use of the go drivers' ReadTimeout dsn setting, exposed via an orchestrator option: MySQLReadTimeoutSeconds means that if you care you can take this into account and you'll generate an error earlier.

**Comment by orkestrov** [comment]
On Thu, Aug 11, 2016 at 11:33 AM, Shlomi Noach <notifications@github.com>
wrote:

> @orkestrov <https://github.com/orkestrov> Booking.com is likely the best
> testbed for this; if you ran this in production for a few days and got no
> error this, I'm happy.
>
> Can you please just elaborate on which version this is of go-sql-driver?
> Is it just latest master? Any particular version number I can write down?
>
Unfortunately, the last stable version of go-sql-driver is 1.2 from Jun
2014. And there're no new tags after that. So I'm making a bet on the last
commit on branch master. It is 0b58b37b66.


> sjmudd convinced me that we should not depend on govendor to build the
> project. So I included driver code and removed .gitignore and build.sh
> changes in the last commit.
>
> I'm afraid I didn't quite follow that^,
>
I used "govendor" to import newer go-sql-driver so that we can track
versions. With that I thought that we don't need to keep driver source in
orchestrator tree anymore because everyone can do "govendor sync" on build.
Which I did: removed the driver and added checks for govendor in the build
script. Then Simon pointed that that way we depend on the authors of
go-sql-driver probably more than we want to: if they decide to move the
driver to a different page we would not be able to build. Which I agreed
and thus checked in the driver back into orchestrator.git.

**Pull request merged**
