### PR TITLE
Pseudo gtid match 5 7 under 5 6

### PR DESCRIPTION
**Pull request by sjmudd**
Fix an issue when moving a 5.7 slave which replicates under a 5.7 intermediate master back under a 5.6 master in pseudo-GTID mode.  Sounds complicated but does happen. 5.7 binlogs contain extra events not on the 5.6 master so the matching process will fail.

This PR consists of two patches:
(1) a "cosmetic" cleanup to GetNextBinlogCoordinatesToMatch to using consistent naming which makes following the logic somewhat easier (for me at least). No functionality changes here but the logic is involved so making it easier to follow should help future readers.
(2) The patch that modifies the behaviour when scanning the 5.7 slave's bin or relay logs under the conditions described.

Hopefully the logic and descriptions make this clear enough to follow.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Storyline: https://github.com/outbrain/orchestrator/issues/248

**Comment by sjmudd** [comment]
I've added a missing test case for this which should complete the changes needed to resolve this.
Hopefully my patch is clear enough to understand.

**Comment by sjmudd** [comment]
Shlomi, are you waiting on anything from me to accept this PR?

**Comment by shlomi-noach** [comment]
@sjmudd no; I just didn't come around to review this yet -- will do so this week!

**Comment by sjmudd** [comment]
I saw that merging this into github/orchestrator is a bit tricky so I'll close this now and make a new PR against the upstream github/orchestrator repo.

**Pull request closed without merging**
