### PR TITLE
Adding godep to handle dependency pinning

### PR DESCRIPTION
**Pull request by grierj**
Version SHAs are tracked in Godeps/Godeps.json
After adding new packages run `godep save -r ./...`  This will rewrite
the imports and add the dependencies to Godeps/_workspace.
I'll write some wiki tidbits soon, but since we're rewriting the
import paths and adding the dependencies to the repo, there's no change
to the build process.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Hi @grierj , still time till this merges; have you looked into the new 1.5 way of godepping? See https://github.com/tools/godep#go-15-vendor-experiment

I will start building orchestrator with Go 1.5 anyhow. The current godep change is daunting. I can see how this solves the problem but it seems very painful to take in. Happy to hear your thoughts.

**Comment by shlomi-noach** [comment]
Rather https://golang.org/cmd/go/#hdr-Vendor_Directories as better documentation

**Comment by shlomi-noach** [comment]
I've attempted, successfuly I believe, the 1.5 experimental vendor packaging. Please take a look at https://github.com/outbrain/orchestrator/pull/142

**Comment by shlomi-noach** [comment]
I'm expecting to be pushing the vendor/ packaging next week, at which time this PR will become redundant.

**Comment by grierj** [comment]
Alright, I'll close this one out and wait for the standard vendoring option.

**Comment by shlomi-noach** [comment]
downstream was merged into master; this includes golang 1.5 vendor packaging.
Also, I'm back on track with accepting new PRs.

**Comment by grierj** [comment]
Sweet! Thanks!

**Pull request closed without merging**
